export const INC_CLICKER = "INC_CLICKER"

// FACEBOOK example api actions types
export const FACEBOOK_EXAMPLE_API_REQUEST = "FACEBOOK_EXAMPLE_API_REQUEST"
export const FACEBOOK_EXAMPLE_API_SUCCESS = "FACEBOOK_EXAMPLE_API_SUCCESS"
export const FACEBOOK_EXAMPLE_API_ERROR = "FACEBOOK_EXAMPLE_API_ERROR"

// LOGIN actions types
export const LOGIN_API_REQUEST = "LOGIN_API_REQUEST"
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS"
export const LOGIN_API_ERROR = "LOGIN_API_ERROR"

export const LOGIN_API_FORGOTPASSWORD_REQUEST = "LOGIN_API_FORGOTPASSWORD_REQUEST"
export const LOGIN_API_FORGOTPASSWORD_SUCCESS = "LOGIN_API_FORGOTPASSWORD_SUCCESS"
export const LOGIN_API_FORGOTPASSWORD_ERROR = "LOGIN_API_FORGOTPASSWORD_ERROR"

export const LOGIN_API_RESET = "LOGIN_API_RESET"
