export const INC_CLICKER = "INC_CLICKER"

// FACEBOOK example api actions types
export const FACEBOOK_EXAMPLE_API_REQUEST = "FACEBOOK_EXAMPLE_API_REQUEST"
export const FACEBOOK_EXAMPLE_API_SUCCESS = "FACEBOOK_EXAMPLE_API_SUCCESS"
export const FACEBOOK_EXAMPLE_API_ERROR = "FACEBOOK_EXAMPLE_API_ERROR"
